Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.provider "docker" do |d|
      d.build_dir = "."
    end

    # ubuntu.vm.provision "shell", inline: <<-SCRIPT
    #   sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    #   sudo useradd kkumtree -m -s /bin/bash
    #   sudo usermod -a -G sudo kkumtree
    #   echo kkumtree:kkumtree | sudo chpasswd
    #   sudo systemctl restart sshd
    # SCRIPT
  end
end
